field.value.helfi_formtool_embed_formtoolembed:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.value.embed_form:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value
